const fs = require('fs');
const path = require('path');

const permissionsPath = path.resolve('C:/Users/KeyurPrajapati/Downloads/permissions.json');
const modulesFilePath = path.resolve(__dirname, '../src/saas/seed/data/modules.data.js');

function readPermissions() {
  const raw = fs.readFileSync(permissionsPath, 'utf8');
  let data;
  try {
    data = JSON.parse(raw);
  } catch (e) {
    console.error('Failed to parse permissions.json:', e.message);
    process.exit(1);
  }

  const table = data.find(x => x && x.type === 'table' && Array.isArray(x.data));
  if (!table) {
    console.error('permissions.json format invalid - missing table.data');
    process.exit(1);
  }

  return table.data; // array of permissions
}

function loadModules() {
  delete require.cache[modulesFilePath];
  const mod = require(modulesFilePath);
  if (!mod || !mod.allModules) throw new Error('modules.data.js did not export allModules');
  return { modules: mod.allModules, modulesAbs: modulesFilePath };
}

function toLabel(name) {
  return name.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function merge(permissions, modules) {
  const notFound = [];

  const permMap = {};
  permissions.forEach(p => { permMap[p.name] = p.id; });

  permissions.forEach(p => {
    const key = `saas.${p.name}`;
    let found = false;

    for (const mod of modules) {
      const act = mod.actions.find(a => a.key === key);
      if (act) {
        // Update id & parentId
        act.id = String(p.id);
        act.parentId = p.parent_id ? String(p.parent_id) : null;
        found = true;
        break;
      }
    }

    if (!found) {
      const prefix = p.name.split('_')[0];
      const target = modules.find(m => m.moduleKey === prefix);
      const newAction = {
        key,
        label: toLabel(p.name),
        id: String(p.id),
        parentId: p.parent_id ? String(p.parent_id) : null,
      };

      if (target) {
        if (!target.actions.some(a => a.key === key)) target.actions.push(newAction);
      } else {
        notFound.push(newAction);
      }
    }
  });

  if (notFound.length) {
    let misc = modules.find(m => m.moduleKey === 'misc_permissions');
    if (!misc) {
      misc = {
        group: 'Misc Permissions',
        moduleKey: 'misc_permissions',
        displayName: 'Misc Permissions',
        actions: [],
      };
      modules.push(misc);
    }
    notFound.forEach(a => {
      if (!misc.actions.some(act => act.key === a.key)) misc.actions.push(a);
    });
  }

  return modules;
}

function writeModules(modules, modulesAbs) {
  const header = `// generated by mergePermissions.js - do not edit by hand\n`;
  const content =
    header +
    `const planExclusions = require("./planExclusions");\n` +
    `const allModules = ${JSON.stringify(modules, null, 2)}\n\n` +
    `module.exports = {\n  allModules,\n\n  getPlanPermissions:(planName)=> {\n    const plan = planExclusions[planName] || {};\n    const { excludeModules = [], excludeActions = {} } = plan;\n    return allModules\n      .filter((module) => !excludeModules.includes(module.moduleKey))\n      .map((module) => {\n        const moduleKey = module.moduleKey;\n        const excluded = excludeActions[moduleKey] || [];\n        const allowedActions = module.actions.filter((a) => !excluded.includes(a.key));\n        return { moduleKey, displayName: module.displayName, visible: true, actions: allowedActions.map((a) => ({ key: a.key, visible:true })) };\n      });\n  }\n};\n`;

  fs.writeFileSync(modulesAbs, content, 'utf8');
  console.log(`modules.data.js updated successfully at ${modulesAbs}`);
}

function main() {
  console.log('Reading permissions.json...');
  const permissions = readPermissions();
  console.log(`Found ${permissions.length} permissions`);

  console.log('Loading modules.data.js...');
  const { modules, modulesAbs } = loadModules();

  console.log('Merging...');
  const merged = merge(permissions, modules);

  console.log('Writing modules.data.js...');
  writeModules(merged, modulesAbs);

  console.log('Done.');
}

main();
